spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saivulavapati/shopping-app-config-server
          clone-on-start: true


server:
  port: 9296